### ISSUE TITLE
Poetry package installation in editable mode

### ISSUE THREAD

**Issue by labdmitriy** [py-pkgs/py-pkgs#113]
Hi,

First of all thanks a lot for your amazing book, it is probably the first resource which provides so much information about Python packages best practices in one place.

I have some notes about poetry package installation in editable mode.

In Chapter 3 you wrote the following:
"poetry install actually installs packages in “editable mode”, which means that it installs a link to your package’s code on your computer (rather than installing it as a independent piece of software)."

I think that it is not currently true since poetry 1.1 and this statement is specified in poetry [documentation](https://python-poetry.org/docs/cli#add):
"Before poetry 1.1 path dependencies were installed in editable mode by default. You should always set the develop attribute explicit, to make sure the behavior is the same for all poetry versions."

But unfortunately provided solution on this documentation page is not working anymore, and there are several issues about that:
- [Editable mode is gone since 1.1.0a2](https://github.com/python-poetry/poetry/issues/2725)
- [How can I install a local version of my package with poetry? non setup.py file](https://github.com/python-poetry/poetry/discussions/1135)

For the second issue, it seems that confirmed [solution](https://github.com/python-poetry/poetry/discussions/1135#discussioncomment-145756) is also not working, and I check that 2 solutions are working now and use it in the projects:
- [Adding setuptools to [build-system] section](https://github.com/python-poetry/poetry/discussions/1135#discussioncomment-1017999)
- [Using python setup.py develop command](https://github.com/python-poetry/poetry/discussions/1135#discussioncomment-679166)

As far as I know, in poetry 1.2 --editable option for poetry add command will be [introduced](https://github.com/python-poetry/poetry/pull/3940), but 1.2 is in beta, and the latest poetry version is 1.1.13 now.

It will be great to hear your thoughts about it and difference between two working methods.

Thank you.

**Comment by labdmitriy** [comment]
I am sorry, I am wrong and now it is installed in editable mode using `poetry install`, I tested it about a year ago and it was not working.
For a reference, I will keep the link here with nice [explanation](https://github.com/python-poetry/poetry/issues/34#issuecomment-1055142428) about that.

**Comment by TomasBeuzen** [comment]
Hi @labdmitriy - firstly, thanks a lot for the kind words, it really means a lot to us 😄 

Secondly, thanks for taking the time to write out your thoughts, and for posting the solution! I think the issue is perfectly summarised in the [explanation you helpfully linked](https://github.com/python-poetry/poetry/issues/34#issuecomment-1055142428). `poetry install` will install the package you are developing in editable mode, and I don't believe that will change anytime soon. That is what we are suggesting in the sentence: *"`poetry install` actually installs packages in “editable mode”, which means that it installs a link to your package’s code on your computer (rather than installing it as a independent piece of software)."* - but I believe we could word that more clearly (which I'll do!).

But you're right that the way to install other path dependencies in editable mode has and is changing. We don't do this in the book, but it's useful to know and I'm glad you brought up this issue, in case others are wondering how to do that (regardless whether this dep uses Poetry or setuptools) is install in editable by default for Poetry < 1.1.

Thanks again and happy coding!

**Comment by labdmitriy** [comment]
Hi @TomasBeuzen,
Thanks a lot for your feedback!
