### ISSUE TITLE
Question: semantic release

### ISSUE THREAD

**Issue by Seth-Julien-de-Lampon** [py-pkgs/py-pkgs#121]
How come (in section 7.2.2) the CI/CD pipeline is not (re-)triggered when the python-semantic-release package commits a new version to the 'main' branch? Shouldn't a new commit count as a `push` and therefore start a new pipeline execution (which would start an infinite loop)?
```
name: ci-cd

on: [push, pull_request]

jobs:
```

**Comment by NickleDave** [comment]
I think the commit from python-semantic-release that gets tagged with a version *will* trigger another run of the CI.

But it will *not* trigger another release, because the commit message associated with releasing a new version won't start with one of the angular keywords that python-semantic-release looks for when it decides whether to make a new release

See: https://python-semantic-release.readthedocs.io/en/latest/commit-log-parsing.html#commit-log-parsing

This is stated in 7.2.2. https://py-pkgs.org/07-releasing-versioning#automatic-version-bumping but I don't see it in chapter 8. Maybe the wording could be a little stronger in 7.2.2., "A release is only triggered when a commit starts with one of the angular keywords", and a call out could be added in 8 that points back to this language

**Comment by TomasBeuzen** [comment]
Hey @Seth-Julien-de-Lampon - fantastic question, thanks for asking (and thanks to Dave for jumping in too). 

Dave is right in that PSR is looking for specific messages and you can massage the behaviour of PSR to avoid pushing changes/making releases in different situations. But the answer to your question about an infinite loop ("recursive behaviour") is actually a GitHub one and not a PSR one. GitHub prevents this kind of recursive situation when using a `GITHUB_TOKEN`. We set up PSR in the CI-CD workflow in [Section 8.5.2](https://py-pkgs.org/08-ci-cd#automatically-creating-a-new-package-version), and we configure the PSR step with a `GITHUB_TOKEN` which allows it to read/write to files in our repo:

```
    - name: Use Python Semantic Release to prepare release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          poetry run semantic-release publish
```

As mentioned above, GitHub prevents recursive workflows when using `GITHUB_TOKEN` - here's the key expert from the [GitHub docs](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow)):

>When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

Certainly worth mentioning this in the text - I'm on parental leave atm but will add this to my list of things to do in a few weeks time :)

**Comment by NickleDave** [comment]
:exploding_head: how did I not know this already

Actually answering so I can learn the real answer from you :smirk_cat: Just let me know when that gets annoying

**Comment by Seth-Julien-de-Lampon** [comment]
Hi @TomasBeuzen, thanks for clarifying! This kind of problem, when something happens (in this case doesn't happen) without me understanding the reason behind it, can really annoy me. I can sleep in peace again!

**Comment by TomasBeuzen** [comment]
No worries - I know exactly the feeling you describe 🙃 And @NickleDave - please don't stop - the help is _always_ appreciated!
