### ISSUE TITLE
[Request] tyephints section

### ISSUE THREAD

**Issue by bendichter** [py-pkgs/py-pkgs#145]
I love this book! This is a fantastic guide for training new research software engineers. I think it would be even better if it had a section in typehints. Would there be any interest in including a section on this?

**Comment by ttimbers** [comment]
Thank-you for the very kind words @bendichter 😊 and thank-you for the suggestions of adding sections on type hints and code style (#146). I agree, these would strengthen the book further and improve it's utility as a resource. We would welcome a pull request for these if you are keen to take a stab at them?

Perhaps type hints could go in "How to Package a Python" [where we introduce functions](https://py-pkgs.org/03-how-to-package-a-python#turning-our-code-into-functions)? And code style could go under the "Continuous integration and deployment" chapter? Perhaps between section [8.4](https://py-pkgs.org/08-ci-cd#setting-up-continuous-integration) and [8.5](https://py-pkgs.org/08-ci-cd#setting-up-continuous-deployment), maybe we could call it "Additional continuous integration checks"? We used to have flake8 checks in the CI chapter a long time ago, but took them out as they frustrated novices. So that is why I am suggesting we label it as "Additional continuous integration checks", so as to make it clear that they are not an absolute requirement.

Or do you have other thoughts where these could go? If so, I would be interested in hearing them! Thanks again!

**Comment by bendichter** [comment]
How would you feel about discussing typehints in a section just after [docstrings](https://py-pkgs.org/06-documentation.html#docstrings)?
