### ISSUE TITLE
Let's talk about suitable package names somewhere

### ISSUE THREAD

**Issue by ttimbers** [py-pkgs/py-pkgs#44]
From teaching a course on packaging, it is becoming clear to me that we should somewhere talk about appropriate package names. For example, what characters are allowed and not (some students use `.` in their package and function names, and that breaks things). Also, I think to use camel case with the Poetry/cookiecutter approach we use, there is something extra we need to do... yes... you need to add this to the `tool.poetry` table in `pyproject.toml` (or at least you had to last year):

```
packages = [
    { include = "convertempPy"},
]
```

**Comment by ttimbers** [comment]
Yes, this still seems to be a thing in Poetry 1.0: https://github.com/python-poetry/poetry/issues/1538

**Comment by TomasBeuzen** [comment]
Adding notes here to add to a future PR:

- [PEP 8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names): "Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged."
- [PEP 0423](https://www.python.org/dev/peps/pep-0423/#pick-memorable-names): "One important thing about a project name is that it be memorable. As an example, celery [21] is not a meaningful name. At first, it is not obvious that it deals with message queuing. But it is memorable, partly because it can be used to feed a RabbitMQ [22] server." "Ask yourself "how would I describe in one sentence what this name is for?", and then "could anyone have guessed that by looking at the name?". As an example, DateUtils [23] is a meaningful name. It is obvious that it deals with utilities for dates. When you are using namespaces, try to make each part meaningful."
