### ISSUE TITLE
use `src` directory in package

### ISSUE THREAD

**Issue by chendaniely** [py-pkgs/py-pkgs#55]
Sorry, I didn't make the connection to post this as an Issue instead of a [tweet](https://twitter.com/chendaniely/status/1376376082610409473).

I got an issue in a package I maintain (https://github.com/chendaniely/pyprojroot/issues/22) that points to and suggests a few resources that state using a `src` layout is a better practice when putting together python packages.

I'm still reading up on it and trying to understand the overall python packaging structure and the role of the `src` folder, but the tl;dr solution is to (https://hynek.me/articles/testing-packaging/#src):

> you just move your packages into a src directory and add a where argument to find_packages() in your setup.py:

```python
setup(
    [...]
    packages=find_packages(where="src"),
    package_dir={"": "src"},
)
```

It seems that the poetry setup doesn't create the `src` folder, and might be something the user does after using poetry, or something that can be incorporated into the UBC cookie-cutter.

Since this book has become *the* resource for me putting together new python packages and using `src` seems to be the best/better practice, this might be something worth looking into and learn about.

**Comment by TomasBeuzen** [comment]
Hey @chendaniely - thanks so much for raising this issue. It's such a coincidence as just this weekend I was thinking about making this change! (we're in the process of significantly revising and updating the book)

I'm going to do a little more research but as you suggest, it's a very easy to change to make in the cookiecutter. And `poetry` does natively support a `src` layout:

```
my-package
├── pyproject.toml
├── README.md
├── src
│   └── my_package
│       └── __init__.py
└── tests
    ├── __init__.py
    └── test_my_package.py
```

 So making this change in the cookiecutter template shouldn't break anything.
 
 ps. your GH tagline: "bow ties are cool". Couldn't agree more 🎀

**Comment by Midnighter** [comment]
Not that my opinion has much weight here but I highly recommend switching to a `src` layout! I've been watching this repo for a while as I also maintain a fairly extensive and opinionated cookiecutter myself https://github.com/opencobra/cookiecutter-python-package/

I was trying to see if I can add anything to this project but haven't gotten around to doing a full comparison yet. I always wanted to write a series of blog posts about why I chose a certain design so I think this project here is awesome!

**Comment by TomasBeuzen** [comment]
Thanks @Midnighter - all opinions are helpful! 😄 

For anyone else reading, the main reason I haven't implemented this as of yet is because I was worried that it could be confusing for beginners, but I think we can easily alleviate that confusion with some well-chosen words in the book. I also didn't realise that `poetry` supported the "src layout" structure before this issue was raised, which makes life much easier. I'll leave this issue open for a few days, but unless I (or anyone) can think of a good reason not to implement this structure, I'll go ahead and implement it in the book and [our cookiecutter](https://github.com/UBC-MDS/cookiecutter-ubc-mds).
