### ISSUE TITLE
Thoughts on the continuation of version control throughout the chapters of the book 

### ISSUE THREAD

**Issue by ttimbers** [py-pkgs/py-pkgs#81]
@TomasBeuzen - I am thinking more and more about the continuation of version control throughout the chapters of the book that follow Chapter 3: How to package a Python. In some ways, I think it adds extra cognitive load that is not needed, but in other ways I think it's good and reinforces good habits. I wonder if there is some balance we can strike between these two. My current idea for this would be too include it, but only at the end of each chapter, as an optional thing they can do if they are following along, expanding their toy package as they read. Also, simplifying the version control expectation (skip the `dev` branch stuff?)  - again, some of our readers might have less experience with version control and we are not teaching it in this book, so our expectation of their knowledge on it should be lower...

Some folks might read the book from end to end and build the toy package along, while others might use this is a reference. So that is why I think moving it to the end of the chapters and simplifying it might be worthwhile. Thoughts?

**Comment by TomasBeuzen** [comment]
I saw your original comment about this last night (in your review of Chapter 4) and have been thinking about it all night! I agree we can move this stuff from the core text and put it at the end of each chapter. I'm inclined to keep the branching for two reasons:

1. because I don't want to advocate for committing directly to `main`
2. because we use PRs in Chapter 8 to demo CI/CD

But perhaps that is too much to think about, especially as we're not discussing `git` in the book (at least not yet, but maybe reviewers will ask us to add that!). I think I could re-write things so that we are committing to `main`, and perhaps have a note somewhere saying that, it's common to use `git` branches for this workflow, to keep the main code base stable before mergining changes etc. In fact, not using branches makes some later chapter simpler because we don't have to show screenshots and walkthroughs of making PRs on GitHub... That was a bit of a brain dump but I think I can see the path in my head now: from Ch3 onwards, move VC stuff to end of chapter as optional, don't use branches
