### ISSUE TITLE
New kid on the block: PyScaffold

### ISSUE THREAD

**Issue by Midnighter** [py-pkgs/py-pkgs#89]
Unfortunately, there is no easy way on GitHub to just send you a quick message.

I really appreciate the effort you're putting into this book and I think it shows. Congratulations on the latest release!

I was wondering if you already have an opinion about https://pyscaffold.org/ which seems to blend package installation/management tools with a cookiecutter like project template?

**Comment by TomasBeuzen** [comment]
Hey there @Midnighter! Thanks a lot for your post and sorry for my *very* delayed response (I started a new job the week you posted this and it just slipped off my radar 🙈). Anyway, I do have an opinion about PyScaffold - it's great! But there are a few reasons why I prefer the cookiecutter + poetry approach we use in py-pkgs:

1. I think PyScaffold is great if you already know what you're doing and understand all the files/tools that come with it. For first-timers or begginer package developers, I feel it might be a tad overwhelming. For example, we don't discuss pre-commits or tox in the book. Despite these being incredibly useful tools, we tried to find a balance between showing tools we felt were important but not too many as to be overwhelming.
2. I like tools that are language agnostic. I think cookiecutter is a valuable tool to know about for creating templates for a diverse range of software (or other) projects, not just Python packages. I know you can combine PyScaffold + Cookiecutter but that would add an extra level of complexity which our book just didn't need.
3. PyScaffold is based on `setuptools`. As you likely would have seen, we advocate for `poetry` as a packaging tool in the book because we feel it offers a level of abstraction and useability above `setuptools` which is perfect for beginner-intermediate packagers (plus dependency handling).

All that being said, PyScaffold is a great project and I'm glad you brought it up. I've added it to #85 to mention it as an alternative package templating tool in the next round of revisions.

**Comment by Midnighter** [comment]
Thank you for your feedback and no worries about the late response.
