### ISSUE TITLE
Issue on page /03-how-to-package-a-python.html

### ISSUE THREAD

**Issue by tarensanders** [py-pkgs/py-pkgs#99]
Hi there,

I'm having trouble getting the example to run. I cannot seem to get the module to import.

I'm at section 3.5. I've installed poetry (`poetry --version` returns `1.1.12`), and set up a conda environment (pycounts).

The guide is a little unclear about if the poetry calls need to be within the conda env or not, but neither works. From the pycounts folder, if I run `poetry install` I get the following

```
The virtual environment found in C:\Users\taren\miniconda3\envs\pycounts seems to be broken.
Recreating virtualenv pycounts-tZwN6m1u-py3.9 in C:\Users\taren\AppData\Local\pypoetry\Cache\virtualenvs\pycounts-tZwN6m1u-py3.9
Installing dependencies from lock file

Installing the current project: pycounts (0.1.0)
```

However, opening a python shell and trying to import the module gives:
```
>>> from pycounts.pycounts import count_words
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pycounts
```

Repeating these steps but not in the conda env does not give the warning about a broken virtual env
```
Installing dependencies from lock file

Installing the current project: pycounts (0.1.0)
```

But the import error is the same:
```
>>> from pycounts.pycounts import count_words
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pycounts'
```

Is there any chance you could help diagnose the issue? I'm using Windows. I've tried:

* A complete wipe of miniconda, including all envs
* Deleting the package and starting again
* Removing and reinstalling poetry

Really appreciate any help.

**Comment by TomasBeuzen** [comment]
HI @tarensanders - thanks for raising this issue. I don't currently have a Windows machine available to step through this but let's see if we can work it out through some debugging (bit of a long reply here).

First and foremost, could you provide the following information:

1. Are you installing `poetry` using the [installation instructions here](https://python-poetry.org/docs/master/#installation), or using something like `pip`? (the former is recommended)
2. What command prompt are you using? We recommend the [Anaconda prompt](https://py-pkgs.org/02-setup#the-command-line-interface) for Windows users, it seems to be the most seamless but poetry can work in other prompts too (e.g., powershell). 
3. Just to be 100% clear, did you call your package `pycounts` when using the cookiecutter? Or something else like `pycounts_<your-intials>`. If the former, your  directory structure should look like below. If that's not the case let me know because that's likely our problem:

```
pycounts
├── ... (other files hidden)
└── src
    └── pycounts
        ├── __init__.py
        └── pycounts.py
```

>The guide is a little unclear about if the poetry calls need to be within the conda env or not, but neither works.

Good to know you felt this way. We set up the virtual environment in [3.5.1](https://py-pkgs.org/03-how-to-package-a-python#create-a-virtual-environment) and the idea is to use this environment throughout the rest of the book, or anytime you're working on your package - we have some text to that effect in the book "Anytime you wish to work on your package, you should activate its virtual environment." but I'll add some more to make it clear (you're not the first to ask this question so the fault lies with us 😄). The `poetry install` command definitely should be run from within this environment, because we want to develop and test our package isolated from the rest of our system.

So, first steps:

1. Remove existing venv: `conda env remove --name pycounts`
2. Create fresh venv: `conda create --name pycounts python=3.9 -y`
2. Active venv: `conda activate pycounts`

Now we'll install the package, running the following command from package root directory:

3. `poetry install`

Verify the package exists in your venv by running:

4. `conda list pycounts`

You should hopefully see something like:

```
# Name                    Version
pycounts                  0.1.0    
```

If so, try importing again. So, still within your venv, try the following:

```
$ python
```

```
>>> from pycounts.pycounts import count_words
```

If you have the same error or another one, please post it here :)

**Comment by tarensanders** [comment]
Hi @TomasBeuzen,

Thanks for the really prompt and detailed reply.

> 1. Are you installing poetry using the installation instructions here, or using something like pip? (the former is recommended)

Yep, installed using the command line installer and not pip or pipx

> What command prompt are you using? We recommend the Anaconda prompt for Windows users, it seems to be the most seamless but poetry can work in other prompts too (e.g., powershell).

Anaconda prompt. Activating conda envs in powershell is a bit of a pain, but I checked and that doesn't work either.

> Just to be 100% clear, did you call your package pycounts when using the cookiecutter? Or something else like pycounts_<your-intials>

Yes, I double checked this. As a sanity check I also created a script with `from pycounts.pycounts import count_words` and added it to the folder. That works (but only because it's finding the module directly, rather than an installed version). My directory structure matches yours.

I reran the process as you described, but it is still failing to install:

```
(pycounts) C:\Users\taren\GitHub\pycounts>poetry install
Creating virtualenv pycounts-tZwN6m1u-py3.9 in C:\Users\taren\AppData\Local\pypoetry\Cache\virtualenvs
Updating dependencies
Resolving dependencies...

Writing lock file

Installing the current project: pycounts (0.1.0)

(pycounts) C:\Users\taren\GitHub\pycounts>conda list pycounts
# packages in environment at C:\Users\taren\miniconda3\envs\pycounts:
#
# Name                    Version                   Build  Channel

```

After looking at issues (https://github.com/python-poetry/poetry/issues/105, https://github.com/python-poetry/poetry/issues/1724 were helpful) and experimenting the only way I was able to get it to work was to:

1. Create and activate the conda env
2. Run `poetry show -v` which gives a path to a virtualenv
3. Manually activate the virtualenv (i.e., `path/to/env/Scripts/activate`)
4. Then (and this is weird) activate the conda env *again*
5. Running `conda list pycounts` still returns nothing, but opening a python shell and importing the module works.

Obviously this is a hack and not the intended method. I'm not too sure how to progress.

**Comment by tarensanders** [comment]
Solved it!

I found [this issue](https://github.com/python-poetry/poetry/issues/4566) in the poetry repo. There's an issue with how `pip` and `conda` store the location of the `python.exe`, and so poetry can't find a version to use. It seems like this has been solved, but it's not in the released version.

Installing the version directly from GitHub (`curl -sSL https://install.python-poetry.org | python - --git https://github.com/python-poetry/poetry.git@master`) works perfectly. Presumably this will end up in the released version soon, so there's likely no reason to update your book. I'll leave this here as a solution for anyone else who has this issue in the meantime.

Thanks again for your help, and for your work creating this book.

**Comment by TomasBeuzen** [comment]
Excellent - thanks very much @tarensanders for posting this, much appreciated!!

>P.S., do you have a BMC or ko-fi so I can buy you a coffee as thanks?

I truly appreciate the gesture but no need for anything other than your kind words! Tiffany and I love developing educational material and it's more than enough reward to know that it's helping people :) Good luck on your packaging journey and please let us know if you run into any other issues.
